name: Devantler.Commons.StringHelpers - Build, Test, Pack, and Push
on:
  push:
    branches: [main]

env:
  NUGET_PACKAGE: src/Devantler.Commons.StringHelpers/bin/Release/Devantler.Commons.StringHelpers.*.nupkg
  NUGET_FEED: https://nuget.pkg.github.com/devantler/index.json
  NUGET_USER: devantler
jobs:
  build-test-pack-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v3.0.3
        with:
          dotnet-version: 7.0.x
      - name: Add NuGet Source
        run: dotnet nuget add source --username $NUGET_USER --password ${{ secrets.GITHUB_TOKEN }} --store-password-in-clear-text --name github "${{ env.NUGET_FEED }}"
      - name: Restore
        run: dotnet restore
      - name: Build
        run: dotnet build --configuration Release --no-restore
      - name: Test
        run: dotnet test --collect:"XPlat Code Coverage" --configuration Release --no-build
      - name: Upload Code Coverage to CodeCov
        uses: codecov/codecov-action@v3
        with:
          files: tests/Devantler.Commons.StringHelpers.Test/TestResults/**/coverage.cobertura.xml
          fail_ci_if_error: true
      - name: Pack
        run: dotnet pack --configuration Release --no-build
      - name: Push
        run: dotnet nuget push $NUGET_PACKAGE --api-key ${{ secrets.GITHUB_TOKEN }} --source "github" --skip-duplicate
